//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hexpoint.Blox.Sounds.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SoundFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SoundFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hexpoint.Blox.Sounds.Resources.SoundFiles", typeof(SoundFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream AddBlock {
            get {
                return ResourceManager.GetStream("AddBlock", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ItemPickup {
            get {
                return ResourceManager.GetStream("ItemPickup", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream JumpOutOfWater {
            get {
                return ResourceManager.GetStream("JumpOutOfWater", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Message {
            get {
                return ResourceManager.GetStream("Message", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PlayerConnect {
            get {
                return ResourceManager.GetStream("PlayerConnect", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PlayerLanding {
            get {
                return ResourceManager.GetStream("PlayerLanding", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream RemoveBlock {
            get {
                return ResourceManager.GetStream("RemoveBlock", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Splash {
            get {
                return ResourceManager.GetStream("Splash", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream TimeToDreamMono {
            get {
                return ResourceManager.GetStream("TimeToDreamMono", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream WaterBubbles {
            get {
                return ResourceManager.GetStream("WaterBubbles", resourceCulture);
            }
        }
    }
}
